# Generated by Django 4.1.7 on 2023-03-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tax',
            new_name='tax_price',
        ),
    ]
