# Generated by Django 4.1.7 on 2023-03-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='secondapp.author')),
                ('address', models.TextField(blank=True, null=True)),
            ],
            bases=('secondapp.author',),
        ),
    ]
